services:
  - type: web
    name: washerbuddie
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: "10000"
      - key: FLASK_APP
        value: "app.py"
      - key: FLASK_ENV
        value: "production"