name: Tests

on:
  push:
    branches:
      - testing_automation
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11', '3.12']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
        pip install pytest-cov

    - name: Run tests with pytest (Windows)
      if: matrix.os == 'windows-latest'
      run: python -m pytest Tests/ --cov=src.Service_Layer --cov-report=term-missing --cov-report=xml:coverage.xml --verbose --import-mode=importlib
    
    - name: Run tests with pytest (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        python -m pytest Tests/ \
          --cov=src.Service_Layer \
          --cov-report=term-missing \
          --cov-report=xml:coverage.xml \
          --verbose \
          --import-mode=importlib

    - name: Debug coverage file
      if: always()
      run: |
        pwd
        ls -la
        echo "Coverage file exists:"
        test -f coverage.xml && echo "Yes" || echo "No"
    
    - name: Upload coverage report
      if: success()
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true